language: node_js
node_js: lts/*
script: npm run webpack
deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: SHMDh1RiRjFqMoA28DIm2z/DxfM2G74kX/lPj6CUINM6aUad9DTFDqJi72RNIACG6AJ6ceekZCAogeCdUBLiT/o6i0BJOl29g0+5otGevNYeUo6RoJ3bR2CnSoU4yknFOtG6yekaYVm02DEPYYqEhtc0c8Dq0n/j5mNfhCqAgxgg5dMHFdOz1ojdaaTLFkkP/KsxQVteZM0zGBn9/cwTe2wKr3Q9yK1x+2ejae5jXBAhBCcKrgHTEh4QFyaLf0i+ZNzw9p4lSHhscHSjhIHiHm8K74qXw3jLLEaAavv3tKuC07GF7VK8KZ9MFZOUeYq87slkzi6PCS3pAb03UYDb1yt4v65Pj8A9PQ0vSTkSGMZlsHnQkV9e1lk9sQ2JsENODzQ79usA+EKs3n+PiZm8RKBDKJnKwbEijKSwtczeHC25bEpwaqqUBwFnNoulLMjlqD43C5jmgio1nH4i6x/w5H2kzOnGt4BE+7NPBuwu1t37eDFlneY7od3IheMFybPcmKJrnCuBywU4rLuiR03vDcJoyCswr1je8HOolpcb53tZW4no3x16j2jmd+lIPF5INC3D02NlWZwD1hwNBkWMyPSLdOldiuse4pXxhnyWoHJIekrgNzCtrapQcX5SxHSxOAGOBBbNsJ7ltsC62iarT/PBbWg9kRvZZSb/ySRgg0c=
  keep-history: true
  local-dir: build
  target-branch: gh-pages
  on:
    branch: master
