language: node_js
node_js: lts/*
script: npm run webpack
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  target-branch: gh-pages
  on:
    branch: master
